# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - windows
julia:
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
git:
  depth: 999999
notifications:
  email: false
